# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# This workflow will install Deno then run Deno lint and test.
# For more information see: https://github.com/denoland/setup-deno

name: ci-cd

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]
    
jobs:
  test:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - name: Display the path
        run: echo $PATH
        shell: bash
      
      - name: copy files to hashiqube
        run: cp -r ./* /home/pushkar/Desktop/vadelabs/hashiqube/simple-node-app
        
      - name: go to hashiqube directory
        run: cd /home/pushkar/Desktop/vadelabs/hashiqube
        
      - name: list files
        run: ls -l
      
      - name: vagrant ssh
        run: vagrant ssh
        
      - name: test1
        run: cd /vagrant/simple-node-app && ls -l
